# Configuration file for ANN IFC data processing

# Training configuration
batch_size: 512                       # Batch size for training and validation 64 original value
num_epochs: 50                        # Number of epochs for training
lr: 0.0008                           # Learning rate for optimizer

# Output configuration
outdir: "./output"                   # Directory to save model outputs and logs

# Flag for train
train_model: False                # A flag for switching train and testing

window_size: 32
test_size: 0.2
